services:
  bw-export:
    container_name: bw-export
    tty: true
    image: 0netx/bw-export:latest
    volumes:
      - D:\_ROOT\repos_my_devops\Bitwarden_Export\export:/var
    environment:
      - BW_CLIENTID=/run/secrets/bwclientid
      - BW_CLIENTSECRET=/run/secrets/bwsecret 
      - BW_PASSWORD=/run/secrets/bwpassword
      - EXPORT_PASSWORD=/run/secrets/exportpassword
      # Optional: Own Vaultwarden/Bitarden selfhosted server
      #- BW_URL_SERVER=<YOUR VAULTWARDER URL SERVER>
      # Optional: If not provided, the service will export all organizations in vault.
      - BW_ORGANIZATIONS_LIST=7fa4314a-7138-4b25-9490-fdea3928a8c2
      # Optional: By default, /var/data/
      # - OUTPUT_PATH=<Output path i.e. /var/data/ >
      # Optional: By default, /var/attachment/
      # - ATTACHMENTS_PATH=<attachment path i.e. /var/attachment/ >
      # Optional: Execution logging file. Please check output path is mapping inside a volume
      # - FILE_LOG=/var/data/bw-export-logfile.log
      # Optional: Keep the maximum number of exports defined. A maximum of X exports will be retained, the oldest exports will be deleted.
      # - KEEP_LAST_BACKUPS=5          
    secrets:
      - bwclientid
      - bwsecret
      - bwpassword

secrets:
  bwclientid:
    file: /mnt/c/.secrets/.bwclientid
  bwsecret:
    file: /mnt/c/.secrets/.bwsecret
  bwpassword:
    file: /mnt/c/.secrets/.bwpassword
  exportpassword:
    file: /mnt/c/.secrets/.exportpassword    