services:
  bw-export:
    container_name: bw-export
    image: 0netx/bw-export:latest
    volumes:
      - ./export:/var/data
      - ./export:/var/attachment
    environment:
      - BW_CLIENTID=<CLIENT ID FROM BITWARDEN API>
      - BW_CLIENTSECRET=<CLIENT SECRET FROM BITWARDEN API>
      - BW_PASSWORD=<BITWARDEN PASSWORD>
      # Optional: Own Vaultwarden/Bitarden selfhosted server
      #- BW_URL_SERVER=<YOUR VAULTWARDER URL SERVER>
      # Optional: By default, /var/data/
      # - OUTPUT_PATH=<Output path i.e. /var/data/ >
      # Optional: By default, /var/attachment/
      # - ATTACHMENTS_PATH=<attachment path i.e. /var/attachment/ >
      - EXPORT_PASSWORD=<Export password. Export will be encrypted with this password>
      # Optional: If not provided, the service will export all organizations in vault.
      # - BW_ORGANIZATIONS_LIST=<Organization list id, comma separated>
      # Optional: Execution logging file. Please check output path is mapping inside a volume
      # - FILE_LOG=/var/data/bw-export-logfile.log
      # Optional: Keep the maximum number of exports defined. A maximum of X exports will be retained, the oldest exports will be deleted.
      # - KEEP_LAST_BACKUPS=5      

